// Code generated from JSON file; DO NOT EDIT.
package sites

// SherlockSites maps site names to their data
var SherlockSites = map[string]SherlockSiteData{
	"Periscope": {
		ErrorType: "status_code",
		URL: "https://www.periscope.tv/%s/",
		URLMain: "https://www.periscope.tv/",
		UsernameClaimed: "blue",
	},
	"Untappd": {
		ErrorType: "status_code",
		URL: "https://untappd.com/user/%s",
		URLMain: "https://untappd.com/",
		UsernameClaimed: "untappd",
	},
	"Wordnik": {
		ErrorMsg: []string{
			"Page Not Found",
		},
		ErrorType: "message",
		RegexCheck: "^[a-zA-Z0-9_.+-]{1,40}$",
		URL: "https://www.wordnik.com/users/%s",
		URLMain: "https://www.wordnik.com/",
		UsernameClaimed: "blue",
	},
	"svidbook": {
		ErrorType: "status_code",
		URL: "https://www.svidbook.ru/user/%s",
		URLMain: "https://www.svidbook.ru/",
		UsernameClaimed: "green",
	},
	"Championat": {
		ErrorType: "status_code",
		URL: "https://www.championat.com/user/%s",
		URLMain: "https://www.championat.com/",
		UsernameClaimed: "blue",
	},
	"Fosstodon": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9_]{1,30}$",
		URL: "https://fosstodon.org/@%s",
		URLMain: "https://fosstodon.org/",
		UsernameClaimed: "blue",
	},
	"Kick": {
		ErrorType: "status_code",
		URL: "https://kick.com/%s",
		URLMain: "https://kick.com/",
		URLProbe: "https://kick.com/api/v2/channels/%s",
		UsernameClaimed: "blue",
	},
	"RubyGems": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]{1,40}",
		URL: "https://rubygems.org/profiles/%s",
		URLMain: "https://rubygems.org/",
		UsernameClaimed: "blue",
	},
	"ShitpostBot5000": {
		ErrorType: "status_code",
		URL: "https://www.shitpostbot.com/user/%s",
		URLMain: "https://www.shitpostbot.com/",
		UsernameClaimed: "blue",
	},
	"YouPorn": {
		ErrorType: "status_code",
		URL: "https://youporn.com/uservids/%s",
		URLMain: "https://youporn.com",
		UsernameClaimed: "blue",
		IsNSFW: true,
	},
	"spletnik": {
		ErrorType: "status_code",
		URL: "https://spletnik.ru/user/%s",
		URLMain: "https://spletnik.ru/",
		UsernameClaimed: "blue",
	},
	"Codecademy": {
		ErrorMsg: []string{
			"This profile could not be found",
		},
		ErrorType: "message",
		URL: "https://www.codecademy.com/profiles/%s",
		URLMain: "https://www.codecademy.com/",
		UsernameClaimed: "blue",
	},
	"Ionic Forum": {
		ErrorType: "status_code",
		URL: "https://forum.ionicframework.com/u/%s",
		URLMain: "https://forum.ionicframework.com/",
		UsernameClaimed: "theblue222",
	},
	"Medium": {
		ErrorMsg: []string{
			"<body",
		},
		ErrorType: "message",
		URL: "https://medium.com/@%s",
		URLMain: "https://medium.com/",
		URLProbe: "https://medium.com/feed/@%s",
		UsernameClaimed: "blue",
	},
	"Vero": {
		ErrorMsg: []string{
			"Not Found",
		},
		ErrorType: "message",
		URL: "https://vero.co/%s",
		URLMain: "https://vero.co/",
		UsernameClaimed: "blue",
		RequestMethod: "GET",
	},
	"mastodon.social": {
		ErrorType: "status_code",
		URL: "https://mastodon.social/@%s",
		URLMain: "https://chaos.social/",
		UsernameClaimed: "Gargron",
	},
	"prog.hu": {
		ErrorType: "response_url",
		URL: "https://prog.hu/azonosito/info/%s",
		URLMain: "https://prog.hu/",
		UsernameClaimed: "Sting",
		ErrorURL: "https://prog.hu/azonosito/info/%s",
	},
	"9GAG": {
		ErrorType: "status_code",
		URL: "https://www.9gag.com/u/%s",
		URLMain: "https://www.9gag.com/",
		UsernameClaimed: "blue",
	},
	"SWAPD": {
		ErrorType: "status_code",
		URL: "https://swapd.co/u/%s",
		URLMain: "https://swapd.co/",
		UsernameClaimed: "swapd",
	},
	"Sportlerfrage": {
		ErrorType: "status_code",
		URL: "https://www.sportlerfrage.net/nutzer/%s",
		URLMain: "https://www.sportlerfrage.net/",
		UsernameClaimed: "sportlerfrage",
	},
	"Apple Discussions": {
		ErrorMsg: []string{
			"The page you tried was not found. You may have used an outdated link or may have typed the address (URL) incorrectly.",
		},
		ErrorType: "message",
		URL: "https://discussions.apple.com/profile/%s",
		URLMain: "https://discussions.apple.com",
		UsernameClaimed: "jason",
	},
	"ChaturBate": {
		ErrorType: "status_code",
		URL: "https://chaturbate.com/%s",
		URLMain: "https://chaturbate.com",
		UsernameClaimed: "cute18cute",
		IsNSFW: true,
	},
	"Coders Rank": {
		ErrorMsg: []string{
			"not a registered member",
		},
		ErrorType: "message",
		RegexCheck: "^[a-zA-Z0-9](?:[a-zA-Z0-9]|-(?=[a-zA-Z0-9])){0,38}$",
		URL: "https://profile.codersrank.io/user/%s/",
		URLMain: "https://codersrank.io/",
		UsernameClaimed: "rootkit7628",
	},
	"GNOME VCS": {
		ErrorType: "response_url",
		RegexCheck: "^(?!-)[a-zA-Z0-9_.-]{2,255}(?<!\\.)$",
		URL: "https://gitlab.gnome.org/%s",
		URLMain: "https://gitlab.gnome.org/",
		UsernameClaimed: "adam",
		ErrorURL: "https://gitlab.gnome.org/%s",
	},
	"GaiaOnline": {
		ErrorMsg: []string{
			"No user ID specified or user does not exist",
		},
		ErrorType: "message",
		URL: "https://www.gaiaonline.com/profiles/%s",
		URLMain: "https://www.gaiaonline.com/",
		UsernameClaimed: "adam",
	},
	"Icons8 Community": {
		ErrorType: "status_code",
		URL: "https://community.icons8.com/u/%s/summary",
		URLMain: "https://community.icons8.com/",
		UsernameClaimed: "thefourCraft",
	},
	"LibraryThing": {
		ErrorMsg: []string{
			"<p>Error: This user doesn't exist</p>",
		},
		ErrorType: "message",
		URL: "https://www.librarything.com/profile/%s",
		URLMain: "https://www.librarything.com/",
		UsernameClaimed: "blue",
		Headers: map[string]string{
			"Cookie": "LTAnonSessionID=3159599315; LTUnifiedCookie=%7B%22areyouhuman%22%3A1%7D; ",
		},
	},
	"OpenStreetMap": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*?$",
		URL: "https://www.openstreetmap.org/user/%s",
		URLMain: "https://www.openstreetmap.org/",
		UsernameClaimed: "blue",
	},
	"Blogger": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://%s.blogspot.com",
		URLMain: "https://www.blogger.com/",
		UsernameClaimed: "blue",
	},
	"Chaos": {
		ErrorType: "status_code",
		URL: "https://chaos.social/@%s",
		URLMain: "https://chaos.social/",
		UsernameClaimed: "ordnung",
	},
	"HackerEarth": {
		ErrorMsg: []string{
			"404. URL not found.",
		},
		ErrorType: "message",
		URL: "https://hackerearth.com/@%s",
		URLMain: "https://hackerearth.com/",
		UsernameClaimed: "naveennamani877",
	},
	"HackerOne": {
		ErrorMsg: []string{
			"Page not found",
		},
		ErrorType: "message",
		URL: "https://hackerone.com/%s",
		URLMain: "https://hackerone.com/",
		UsernameClaimed: "stok",
	},
	"Image Fap": {
		ErrorMsg: []string{
			"Not found",
		},
		ErrorType: "message",
		URL: "https://www.imagefap.com/profile/%s",
		URLMain: "https://www.imagefap.com/",
		UsernameClaimed: "blue",
		IsNSFW: true,
	},
	"Sbazar.cz": {
		ErrorType: "status_code",
		URL: "https://www.sbazar.cz/%s",
		URLMain: "https://www.sbazar.cz/",
		UsernameClaimed: "blue",
	},
	"Splits.io": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*?$",
		URL: "https://splits.io/users/%s",
		URLMain: "https://splits.io",
		UsernameClaimed: "cambosteve",
	},
	"Star Citizen": {
		ErrorMsg: []string{
			"404",
		},
		ErrorType: "message",
		URL: "https://robertsspaceindustries.com/citizens/%s",
		URLMain: "https://robertsspaceindustries.com/",
		UsernameClaimed: "blue",
	},
	"Issuu": {
		ErrorType: "status_code",
		URL: "https://issuu.com/%s",
		URLMain: "https://issuu.com/",
		UsernameClaimed: "jenny",
	},
	"Kik": {
		ErrorMsg: []string{
			"The page you requested was not found",
		},
		ErrorType: "message",
		URL: "https://kik.me/%s",
		URLMain: "http://kik.me/",
		URLProbe: "https://ws2.kik.com/user/%s",
		UsernameClaimed: "blue",
	},
	"Tuna": {
		ErrorType: "status_code",
		RegexCheck: "^[a-z0-9]{4,40}$",
		URL: "https://tuna.voicemod.net/user/%s",
		URLMain: "https://tuna.voicemod.net/",
		UsernameClaimed: "bob",
	},
	"Bazar.cz": {
		ErrorType: "response_url",
		URL: "https://www.bazar.cz/%s/",
		URLMain: "https://www.bazar.cz/",
		UsernameClaimed: "pianina",
		ErrorURL: "https://www.bazar.cz/error404.aspx",
	},
	"1337x": {
		ErrorMsg: []string{
			"<title>Error something went wrong.</title>",
			"<head><title>404 Not Found</title></head>",
		},
		ErrorType: "message",
		RegexCheck: "^[A-Za-z0-9]{4,12}$",
		URL: "https://www.1337x.to/user/%s/",
		URLMain: "https://www.1337x.to/",
		UsernameClaimed: "FitGirl",
	},
	"BraveCommunity": {
		ErrorType: "status_code",
		URL: "https://community.brave.com/u/%s/",
		URLMain: "https://community.brave.com/",
		UsernameClaimed: "blue",
	},
	"Coroflot": {
		ErrorType: "status_code",
		URL: "https://www.coroflot.com/%s",
		URLMain: "https://coroflot.com/",
		UsernameClaimed: "blue",
	},
	"Fandom": {
		ErrorType: "status_code",
		URL: "https://www.fandom.com/u/%s",
		URLMain: "https://www.fandom.com/",
		UsernameClaimed: "Jungypoo",
	},
	"Harvard Scholar": {
		ErrorType: "status_code",
		URL: "https://scholar.harvard.edu/%s",
		URLMain: "https://scholar.harvard.edu/",
		UsernameClaimed: "ousmanekane",
	},
	"Joplin Forum": {
		ErrorType: "status_code",
		URL: "https://discourse.joplinapp.org/u/%s",
		URLMain: "https://discourse.joplinapp.org/",
		UsernameClaimed: "laurent",
	},
	"Needrom": {
		ErrorType: "status_code",
		URL: "https://www.needrom.com/author/%s/",
		URLMain: "https://www.needrom.com/",
		UsernameClaimed: "needrom",
	},
	"BitBucket": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9-_]{1,30}$",
		URL: "https://bitbucket.org/%s/",
		URLMain: "https://bitbucket.org/",
		UsernameClaimed: "white",
	},
	"IRC-Galleria": {
		ErrorType: "response_url",
		URL: "https://irc-galleria.net/user/%s",
		URLMain: "https://irc-galleria.net/",
		UsernameClaimed: "appas",
		ErrorURL: "https://irc-galleria.net/users/search?username=%s",
	},
	"OurDJTalk": {
		ErrorMsg: []string{
			"The specified member cannot be found",
		},
		ErrorType: "message",
		URL: "https://ourdjtalk.com/members?username=%s",
		URLMain: "https://ourdjtalk.com/",
		UsernameClaimed: "steve",
	},
	"Pokemon Showdown": {
		ErrorType: "status_code",
		URL: "https://pokemonshowdown.com/users/%s",
		URLMain: "https://pokemonshowdown.com",
		UsernameClaimed: "blue",
	},
	"SmugMug": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z]{1,35}$",
		URL: "https://%s.smugmug.com",
		URLMain: "https://smugmug.com",
		UsernameClaimed: "winchester",
	},
	"TorrentGalaxy": {
		ErrorMsg: []string{
			"<title>TGx:Can't show details</title>",
		},
		ErrorType: "message",
		RegexCheck: "^[A-Za-z0-9]{3,15}$",
		URL: "https://torrentgalaxy.to/profile/%s",
		URLMain: "https://torrentgalaxy.to/",
		UsernameClaimed: "GalaxyRG",
	},
	"eintracht": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*?$",
		URL: "https://community.eintracht.de/fans/%s",
		URLMain: "https://eintracht.de",
		UsernameClaimed: "blue",
	},
	"znanylekarz.pl": {
		ErrorType: "status_code",
		URL: "https://www.znanylekarz.pl/%s",
		URLMain: "https://znanylekarz.pl",
		UsernameClaimed: "janusz-,nowak",
	},
	"ImgUp.cz": {
		ErrorType: "status_code",
		URL: "https://imgup.cz/%s",
		URLMain: "https://imgup.cz/",
		UsernameClaimed: "adam",
	},
	"PSNProfiles.com": {
		ErrorType: "response_url",
		URL: "https://psnprofiles.com/%s",
		URLMain: "https://psnprofiles.com/",
		UsernameClaimed: "blue",
		ErrorURL: "https://psnprofiles.com/?psnId=%s",
	},
	"SportsRU": {
		ErrorType: "status_code",
		URL: "https://www.sports.ru/profile/%s/",
		URLMain: "https://www.sports.ru/",
		UsernameClaimed: "blue",
	},
	"npm": {
		ErrorType: "status_code",
		URL: "https://www.npmjs.com/~%s",
		URLMain: "https://www.npmjs.com/",
		UsernameClaimed: "kennethsweezy",
	},
	"Ask Fedora": {
		ErrorType: "status_code",
		URL: "https://ask.fedoraproject.org/u/%s",
		URLMain: "https://ask.fedoraproject.org/",
		UsernameClaimed: "red",
	},
	"Blipfoto": {
		ErrorType: "status_code",
		URL: "https://www.blipfoto.com/%s",
		URLMain: "https://www.blipfoto.com/",
		UsernameClaimed: "blue",
	},
	"Reisefrage": {
		ErrorType: "status_code",
		URL: "https://www.reisefrage.net/nutzer/%s",
		URLMain: "https://www.reisefrage.net/",
		UsernameClaimed: "reisefrage",
	},
	"babyblogRU": {
		ErrorType: "response_url",
		URL: "https://www.babyblog.ru/user/%s",
		URLMain: "https://www.babyblog.ru/",
		UsernameClaimed: "blue",
		ErrorURL: "https://www.babyblog.ru/",
	},
	"livelib": {
		ErrorType: "status_code",
		URL: "https://www.livelib.ru/reader/%s",
		URLMain: "https://www.livelib.ru/",
		UsernameClaimed: "blue",
	},
	"Archive.org": {
		ErrorMsg: []string{
			"could not fetch an account with user item identifier",
			"The resource could not be found",
			"Internet Archive services are temporarily offline",
		},
		ErrorType: "message",
		URL: "https://archive.org/details/@%s",
		URLMain: "https://archive.org",
		URLProbe: "https://archive.org/details/@%s?noscript=true",
		UsernameClaimed: "blue",
	},
	"ArtStation": {
		ErrorType: "status_code",
		URL: "https://www.artstation.com/%s",
		URLMain: "https://www.artstation.com/",
		UsernameClaimed: "Blue",
	},
	"BoardGameGeek": {
		ErrorMsg: []string{
			"User not found",
		},
		ErrorType: "message",
		RegexCheck: "^[a-zA-Z0-9_]*$",
		URL: "https://boardgamegeek.com/user/%s",
		URLMain: "https://boardgamegeek.com",
		UsernameClaimed: "blue",
	},
	"Gravatar": {
		ErrorType: "status_code",
		RegexCheck: "^((?!\\.).)*$",
		URL: "http://en.gravatar.com/%s",
		URLMain: "http://en.gravatar.com/",
		UsernameClaimed: "blue",
	},
	"LushStories": {
		ErrorType: "status_code",
		URL: "https://www.lushstories.com/profile/%s",
		URLMain: "https://www.lushstories.com/",
		UsernameClaimed: "chris_brown",
		IsNSFW: true,
	},
	"VirusTotal": {
		ErrorType: "status_code",
		URL: "https://www.virustotal.com/gui/user/%s",
		URLMain: "https://www.virustotal.com/",
		URLProbe: "https://www.virustotal.com/ui/users/%s/avatar",
		UsernameClaimed: "blue",
		RequestMethod: "GET",
	},
	"leasehackr": {
		ErrorType: "status_code",
		URL: "https://forum.leasehackr.com/u/%s/summary/",
		URLMain: "https://forum.leasehackr.com/",
		UsernameClaimed: "adam",
	},
	"BiggerPockets": {
		ErrorType: "status_code",
		URL: "https://www.biggerpockets.com/users/%s",
		URLMain: "https://www.biggerpockets.com/",
		UsernameClaimed: "blue",
	},
	"Discord": {
		ErrorMsg: []string{
			"{\"taken\":false}",
			"The resource is being rate limited",
		},
		ErrorType: "message",
		URL: "https://discord.com",
		URLMain: "https://discord.com/",
		URLProbe: "https://discord.com/api/v9/unique-username/username-attempt-unauthed",
		UsernameClaimed: "blue",
		Headers: map[string]string{
			"Content-Type": "application/json",
		},
		RequestMethod: "POST",
		RequestPayload: "{\"username\":\"%s\"}",
	},
	"MMORPG Forum": {
		ErrorType: "status_code",
		URL: "https://forums.mmorpg.com/profile/%s",
		URLMain: "https://forums.mmorpg.com/",
		UsernameClaimed: "goku",
	},
	"Mydramalist": {
		ErrorMsg: []string{
			"Sign in - MyDramaList",
		},
		ErrorType: "message",
		URL: "https://www.mydramalist.com/profile/%s",
		URLMain: "https://mydramalist.com",
		UsernameClaimed: "elhadidy12398",
	},
	"PocketStars": {
		ErrorMsg: []string{
			"Join Your Favorite Adult Stars",
		},
		ErrorType: "message",
		URL: "https://pocketstars.com/%s",
		URLMain: "https://pocketstars.com/",
		UsernameClaimed: "hacker",
		IsNSFW: true,
	},
	"ResearchGate": {
		ErrorType: "response_url",
		RegexCheck: "\\w+_\\w+",
		URL: "https://www.researchgate.net/profile/%s",
		URLMain: "https://www.researchgate.net/",
		UsernameClaimed: "John_Smith",
		ErrorURL: "https://www.researchgate.net/directory/profiles",
	},
	"Snapchat": {
		ErrorType: "status_code",
		RegexCheck: "^[a-z][a-z-_.]{3,15}",
		URL: "https://www.snapchat.com/add/%s",
		URLMain: "https://www.snapchat.com",
		UsernameClaimed: "teamsnapchat",
		RequestMethod: "GET",
	},
	"WebNode": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.webnode.cz/",
		URLMain: "https://www.webnode.cz/",
		UsernameClaimed: "radkabalcarova",
	},
	"Airbit": {
		ErrorType: "status_code",
		URL: "https://airbit.com/%s",
		URLMain: "https://airbit.com/",
		UsernameClaimed: "airbit",
	},
	"Airliners": {
		ErrorType: "status_code",
		URL: "https://www.airliners.net/user/%s/profile/photos",
		URLMain: "https://www.airliners.net/",
		UsernameClaimed: "yushinlin",
	},
	"Audiojungle": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9_]+$",
		URL: "https://audiojungle.net/user/%s",
		URLMain: "https://audiojungle.net/",
		UsernameClaimed: "blue",
	},
	"VK": {
		ErrorType: "response_url",
		URL: "https://vk.com/%s",
		URLMain: "https://vk.com/",
		UsernameClaimed: "brown",
		ErrorURL: "https://www.quora.com/profile/%s",
	},
	"Wikidot": {
		ErrorMsg: []string{
			"User does not exist.",
		},
		ErrorType: "message",
		URL: "http://www.wikidot.com/user:info/%s",
		URLMain: "http://www.wikidot.com/",
		UsernameClaimed: "blue",
	},
	"YandexMusic": {
		ErrorMsg: []string{
			"Ошибка 404",
			"<meta name=\"description\" content=\"Открывайте новую музыку каждый день.",
			"<input type=\"submit\" class=\"CheckboxCaptcha-Button\"",
		},
		ErrorType: "message",
		URL: "https://music.yandex/users/%s/playlists",
		URLMain: "https://music.yandex",
		UsernameClaimed: "ya.,playlist",
	},
	"Crowdin": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9._-]{2,255}$",
		URL: "https://crowdin.com/profile/%s",
		URLMain: "https://crowdin.com/",
		UsernameClaimed: "blue",
	},
	"DeviantART": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://%s.deviantart.com",
		URLMain: "https://deviantart.com",
		UsernameClaimed: "blue",
	},
	"Gradle": {
		ErrorType: "status_code",
		RegexCheck: "^(?!-)[a-zA-Z0-9-]{3,}(?<!-)$",
		URL: "https://plugins.gradle.org/u/%s",
		URLMain: "https://gradle.org/",
		UsernameClaimed: "jetbrains",
	},
	"MixCloud": {
		ErrorType: "status_code",
		URL: "https://www.mixcloud.com/%s/",
		URLMain: "https://www.mixcloud.com/",
		URLProbe: "https://api.mixcloud.com/%s/",
		UsernameClaimed: "jenny",
	},
	"Patreon": {
		ErrorType: "status_code",
		URL: "https://www.patreon.com/%s",
		URLMain: "https://www.patreon.com/",
		UsernameClaimed: "blue",
	},
	"PentesterLab": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w]{4,30}$",
		URL: "https://pentesterlab.com/profile/%s",
		URLMain: "https://pentesterlab.com/",
		UsernameClaimed: "0day",
	},
	"Spells8": {
		ErrorType: "status_code",
		URL: "https://forum.spells8.com/u/%s",
		URLMain: "https://spells8.com",
		UsernameClaimed: "susurrus",
	},
	"TnAFlix": {
		ErrorType: "status_code",
		URL: "https://www.tnaflix.com/profile/%s",
		URLMain: "https://www.tnaflix.com/",
		UsernameClaimed: "hacker",
		IsNSFW: true,
	},
	"BuzzFeed": {
		ErrorType: "status_code",
		URL: "https://buzzfeed.com/%s",
		URLMain: "https://buzzfeed.com/",
		UsernameClaimed: "blue",
	},
	"TrashboxRU": {
		ErrorType: "status_code",
		RegexCheck: "^[A-Za-z0-9_-]{3,16}$",
		URL: "https://trashbox.ru/users/%s",
		URLMain: "https://trashbox.ru/",
		UsernameClaimed: "blue",
	},
	"Tweakers": {
		ErrorType: "status_code",
		URL: "https://tweakers.net/gallery/%s",
		URLMain: "https://tweakers.net",
		UsernameClaimed: "femme",
	},
	"Velog": {
		ErrorType: "status_code",
		URL: "https://velog.io/@%s/posts",
		URLMain: "https://velog.io/",
		UsernameClaimed: "qlgks1",
	},
	"Wykop": {
		ErrorType: "status_code",
		URL: "https://www.wykop.pl/ludzie/%s",
		URLMain: "https://www.wykop.pl",
		UsernameClaimed: "blue",
	},
	"jeuxvideo": {
		ErrorType: "status_code",
		URL: "https://www.jeuxvideo.com/profil/%s",
		URLMain: "https://www.jeuxvideo.com",
		URLProbe: "https://www.jeuxvideo.com/profil/%s?mode=infos",
		UsernameClaimed: "adam",
		RequestMethod: "GET",
	},
	"Itemfix": {
		ErrorMsg: []string{
			"<title>ItemFix - Channel: </title>",
		},
		ErrorType: "message",
		URL: "https://www.itemfix.com/c/%s",
		URLMain: "https://www.itemfix.com/",
		UsernameClaimed: "blue",
	},
	"TETR.IO": {
		ErrorMsg: []string{
			"No such user!",
		},
		ErrorType: "message",
		URL: "https://ch.tetr.io/u/%s",
		URLMain: "https://tetr.io",
		URLProbe: "https://ch.tetr.io/api/users/%s",
		UsernameClaimed: "osk",
	},
	"Wattpad": {
		ErrorType: "status_code",
		URL: "https://www.wattpad.com/user/%s",
		URLMain: "https://www.wattpad.com/",
		URLProbe: "https://www.wattpad.com/api/v3/users/%s/",
		UsernameClaimed: "Dogstho7951",
	},
	"chaos.social": {
		ErrorType: "status_code",
		URL: "https://chaos.social/@%s",
		URLMain: "https://chaos.social/",
		UsernameClaimed: "rixx",
	},
	"uid": {
		ErrorType: "status_code",
		URL: "http://uid.me/%s",
		URLMain: "https://uid.me/",
		UsernameClaimed: "blue",
	},
	"Contently": {
		ErrorType: "response_url",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://%s.contently.com/",
		URLMain: "https://contently.com/",
		UsernameClaimed: "jordanteicher",
		ErrorURL: "https://contently.com",
	},
	"DEV Community": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://dev.to/%s",
		URLMain: "https://dev.to/",
		UsernameClaimed: "blue",
	},
	"Naver": {
		ErrorType: "status_code",
		URL: "https://blog.naver.com/%s",
		URLMain: "https://naver.com",
		UsernameClaimed: "blue",
	},
	"Velomania": {
		ErrorMsg: []string{
			"Пользователь не зарегистрирован и не имеет профиля для просмотра.",
		},
		ErrorType: "message",
		URL: "https://forum.velomania.ru/member.php?username=%s",
		URLMain: "https://forum.velomania.ru/",
		UsernameClaimed: "red",
	},
	"satsisRU": {
		ErrorType: "status_code",
		URL: "https://satsis.info/user/%s",
		URLMain: "https://satsis.info/",
		UsernameClaimed: "red",
	},
	"Disqus": {
		ErrorType: "status_code",
		URL: "https://disqus.com/%s",
		URLMain: "https://disqus.com/",
		UsernameClaimed: "blue",
	},
	"Freelance.habr": {
		ErrorMsg: []string{
			"<div class=\"icon_user_locked\"></div>",
		},
		ErrorType: "message",
		RegexCheck: "^((?!\\.).)*$",
		URL: "https://freelance.habr.com/freelancers/%s",
		URLMain: "https://freelance.habr.com/",
		UsernameClaimed: "adam",
	},
	"NICommunityForum": {
		ErrorMsg: []string{
			"The page you were looking for could not be found.",
		},
		ErrorType: "message",
		URL: "https://community.native-instruments.com/profile/%s",
		URLMain: "https://www.native-instruments.com/forum/",
		UsernameClaimed: "jambert",
	},
	"authorSTREAM": {
		ErrorType: "status_code",
		URL: "http://www.authorstream.com/%s/",
		URLMain: "http://www.authorstream.com/",
		UsernameClaimed: "blue",
	},
	"fl": {
		ErrorType: "status_code",
		URL: "https://www.fl.ru/users/%s",
		URLMain: "https://www.fl.ru/",
		UsernameClaimed: "blue",
	},
	"Archive of Our Own": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*?$",
		URL: "https://archiveofourown.org/users/%s",
		URLMain: "https://archiveofourown.org/",
		UsernameClaimed: "test",
	},
	"Envato Forum": {
		ErrorType: "status_code",
		URL: "https://forums.envato.com/u/%s",
		URLMain: "https://forums.envato.com/",
		UsernameClaimed: "enabled",
	},
	"IFTTT": {
		ErrorType: "status_code",
		RegexCheck: "^[A-Za-z0-9]{3,35}$",
		URL: "https://www.ifttt.com/p/%s",
		URLMain: "https://www.ifttt.com/",
		UsernameClaimed: "blue",
	},
	"Signal": {
		ErrorMsg: []string{
			"Oops! That page doesn’t exist or is private.",
		},
		ErrorType: "message",
		URL: "https://community.signalusers.org/u/%s",
		URLMain: "https://community.signalusers.org",
		UsernameClaimed: "jlund",
	},
	"drive2": {
		ErrorType: "status_code",
		URL: "https://www.drive2.ru/users/%s",
		URLMain: "https://www.drive2.ru/",
		UsernameClaimed: "blue",
	},
	"geocaching": {
		ErrorType: "status_code",
		URL: "https://www.geocaching.com/p/default.aspx?u=%s",
		URLMain: "https://www.geocaching.com/",
		UsernameClaimed: "blue",
	},
	"Bandcamp": {
		ErrorType: "status_code",
		URL: "https://www.bandcamp.com/%s",
		URLMain: "https://www.bandcamp.com/",
		UsernameClaimed: "blue",
	},
	"Freesound": {
		ErrorType: "status_code",
		URL: "https://freesound.org/people/%s/",
		URLMain: "https://freesound.org/",
		UsernameClaimed: "blue",
	},
	"Linktree": {
		ErrorMsg: []string{
			"\"statusCode\":404",
		},
		ErrorType: "message",
		RegexCheck: "^[\\w\\.]{2,30}$",
		URL: "https://linktr.ee/%s",
		URLMain: "https://linktr.ee/",
		UsernameClaimed: "anne",
	},
	"PCGamer": {
		ErrorMsg: []string{
			"The specified member cannot be found. Please enter a member's entire name.",
		},
		ErrorType: "message",
		URL: "https://forums.pcgamer.com/members/?username=%s",
		URLMain: "https://pcgamer.com",
		UsernameClaimed: "admin",
	},
	"Vimeo": {
		ErrorType: "status_code",
		URL: "https://vimeo.com/%s",
		URLMain: "https://vimeo.com/",
		UsernameClaimed: "blue",
	},
	"kofi": {
		ErrorType: "response_url",
		URL: "https://ko-fi.com/%s",
		URLMain: "https://ko-fi.com",
		UsernameClaimed: "yeahkenny",
		ErrorURL: "https://ko-fi.com/art?=redirect",
	},
	"osu!": {
		ErrorType: "status_code",
		URL: "https://osu.ppy.sh/users/%s",
		URLMain: "https://osu.ppy.sh/",
		UsernameClaimed: "blue",
	},
	"toster": {
		ErrorType: "status_code",
		URL: "https://www.toster.ru/user/%s/answers",
		URLMain: "https://www.toster.ru/",
		UsernameClaimed: "adam",
	},
	"BongaCams": {
		ErrorType: "status_code",
		URL: "https://pt.bongacams.com/profile/%s",
		URLMain: "https://pt.bongacams.com",
		UsernameClaimed: "asuna-,black",
		IsNSFW: true,
	},
	"Exposure": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9-]{1,63}$",
		URL: "https://%s.exposure.co/",
		URLMain: "https://exposure.co/",
		UsernameClaimed: "jonasjacobsson",
	},
	"Forum Ophilia": {
		ErrorMsg: []string{
			"that user does not exist",
		},
		ErrorType: "message",
		URL: "https://www.forumophilia.com/profile.php?mode=viewprofile&u=%s",
		URLMain: "https://www.forumophilia.com/",
		UsernameClaimed: "bob",
		IsNSFW: true,
	},
	"Genius (Users)": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9]*?$",
		URL: "https://genius.com/%s",
		URLMain: "https://genius.com/",
		UsernameClaimed: "genius",
	},
	"GetMyUni": {
		ErrorType: "status_code",
		URL: "https://www.getmyuni.com/user/%s",
		URLMain: "https://getmyuni.com/",
		UsernameClaimed: "Upneet.,Grover17",
	},
	"Rumble": {
		ErrorType: "status_code",
		URL: "https://rumble.com/user/%s",
		URLMain: "https://rumble.com/",
		UsernameClaimed: "John",
	},
	"Slides": {
		ErrorType: "status_code",
		URL: "https://slides.com/%s",
		URLMain: "https://slides.com/",
		UsernameClaimed: "blue",
		ErrorCode: 204,
	},
	"AniWorld": {
		ErrorMsg: []string{
			"Dieses Profil ist nicht verfügbar",
		},
		ErrorType: "message",
		URL: "https://aniworld.to/user/profil/%s",
		URLMain: "https://aniworld.to/",
		UsernameClaimed: "blue",
	},
	"Bezuzyteczna": {
		ErrorType: "status_code",
		URL: "https://bezuzyteczna.pl/uzytkownicy/%s",
		URLMain: "https://bezuzyteczna.pl",
		UsernameClaimed: "Jackson",
	},
	"Eintracht Frankfurt Forum": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*?$",
		URL: "https://community.eintracht.de/fans/%s",
		URLMain: "https://community.eintracht.de/",
		UsernameClaimed: "mmammu",
	},
	"Lichess": {
		ErrorType: "status_code",
		URL: "https://lichess.org/@/%s",
		URLMain: "https://lichess.org",
		UsernameClaimed: "john",
	},
	"Sporcle": {
		ErrorType: "status_code",
		URL: "https://www.sporcle.com/user/%s/people",
		URLMain: "https://www.sporcle.com/",
		UsernameClaimed: "blue",
	},
	"dailykos": {
		ErrorMsg: []string{
			"{\"result\":true,\"message\":null}",
		},
		ErrorType: "message",
		URL: "https://www.dailykos.com/user/%s",
		URLMain: "https://www.dailykos.com",
		URLProbe: "https://www.dailykos.com/signup/check_nickname?nickname=%s",
		UsernameClaimed: "blue",
	},
	"BioHacking": {
		ErrorType: "status_code",
		URL: "https://forum.dangerousthings.com/u/%s",
		URLMain: "https://forum.dangerousthings.com/",
		UsernameClaimed: "blue",
	},
	"Houzz": {
		ErrorType: "status_code",
		URL: "https://houzz.com/user/%s",
		URLMain: "https://houzz.com/",
		UsernameClaimed: "blue",
	},
	"LeetCode": {
		ErrorType: "status_code",
		URL: "https://leetcode.com/%s",
		URLMain: "https://leetcode.com/",
		UsernameClaimed: "blue",
	},
	"Scribd": {
		ErrorMsg: []string{
			"Page not found",
		},
		ErrorType: "message",
		URL: "https://www.scribd.com/%s",
		URLMain: "https://www.scribd.com/",
		UsernameClaimed: "blue",
	},
	"xHamster": {
		ErrorType: "status_code",
		URL: "https://xhamster.com/users/%s",
		URLMain: "https://xhamster.com",
		URLProbe: "https://xhamster.com/users/%s?old_browser=true",
		UsernameClaimed: "blue",
		IsNSFW: true,
	},
	"HackerNews": {
		ErrorMsg: []string{
			"No such user.",
			"Sorry.",
		},
		ErrorType: "message",
		URL: "https://news.ycombinator.com/user?id=%s",
		URLMain: "https://news.ycombinator.com/",
		UsernameClaimed: "blue",
	},
	"Listed": {
		ErrorType: "response_url",
		URL: "https://listed.to/@%s",
		URLMain: "https://listed.to/",
		UsernameClaimed: "listed",
		ErrorURL: "https://listed.to/@%s",
	},
	"ProductHunt": {
		ErrorType: "status_code",
		URL: "https://www.producthunt.com/@%s",
		URLMain: "https://www.producthunt.com/",
		UsernameClaimed: "jenny",
	},
	"Warrior Forum": {
		ErrorType: "status_code",
		URL: "https://www.warriorforum.com/members/%s.html",
		URLMain: "https://www.warriorforum.com/",
		UsernameClaimed: "blue",
	},
	"Jellyfin Weblate": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9@._-]{1,150}$",
		URL: "https://translate.jellyfin.org/user/%s/",
		URLMain: "https://translate.jellyfin.org/",
		UsernameClaimed: "EraYaN",
	},
	"Kaggle": {
		ErrorType: "status_code",
		URL: "https://www.kaggle.com/%s",
		URLMain: "https://www.kaggle.com/",
		UsernameClaimed: "dansbecker",
	},
	"Bookcrossing": {
		ErrorType: "status_code",
		URL: "https://www.bookcrossing.com/mybookshelf/%s/",
		URLMain: "https://www.bookcrossing.com/",
		UsernameClaimed: "blue",
	},
	"CGTrader": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*?$",
		URL: "https://www.cgtrader.com/%s",
		URLMain: "https://www.cgtrader.com",
		UsernameClaimed: "blue",
	},
	"Coinvote": {
		ErrorType: "status_code",
		URL: "https://coinvote.cc/profile/%s",
		URLMain: "https://coinvote.cc/",
		UsernameClaimed: "blue",
	},
	"Itch.io": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.itch.io/",
		URLMain: "https://itch.io/",
		UsernameClaimed: "blue",
	},
	"Codeberg": {
		ErrorType: "status_code",
		URL: "https://codeberg.org/%s",
		URLMain: "https://codeberg.org/",
		UsernameClaimed: "blue",
	},
	"GeeksforGeeks": {
		ErrorType: "status_code",
		URL: "https://auth.geeksforgeeks.org/user/%s",
		URLMain: "https://www.geeksforgeeks.org/",
		UsernameClaimed: "adam",
	},
	"GitHub": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9](?:[a-zA-Z0-9]|-(?=[a-zA-Z0-9])){0,38}$",
		URL: "https://www.github.com/%s",
		URLMain: "https://www.github.com/",
		UsernameClaimed: "blue",
	},
	"NotABug.org": {
		ErrorType: "status_code",
		URL: "https://notabug.org/%s",
		URLMain: "https://notabug.org/",
		URLProbe: "https://notabug.org/%s/followers",
		UsernameClaimed: "red",
	},
	"akniga": {
		ErrorType: "status_code",
		URL: "https://akniga.org/profile/%s",
		URLMain: "https://akniga.org/profile/blue/",
		UsernameClaimed: "blue",
	},
	"Discuss.Elastic.co": {
		ErrorType: "status_code",
		URL: "https://discuss.elastic.co/u/%s",
		URLMain: "https://discuss.elastic.co/",
		UsernameClaimed: "blue",
	},
	"Flightradar24": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9_]{3,20}$",
		URL: "https://my.flightradar24.com/%s",
		URLMain: "https://www.flightradar24.com/",
		UsernameClaimed: "jebbrooks",
	},
	"Pinkbike": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*?$",
		URL: "https://www.pinkbike.com/u/%s/",
		URLMain: "https://www.pinkbike.com/",
		UsernameClaimed: "blue",
	},
	"mercadolivre": {
		ErrorType: "status_code",
		URL: "https://www.mercadolivre.com.br/perfil/%s",
		URLMain: "https://www.mercadolivre.com.br",
		UsernameClaimed: "blue",
	},
	"nnRU": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.www.nn.ru/",
		URLMain: "https://www.nn.ru/",
		UsernameClaimed: "blue",
	},
	"Autofrage": {
		ErrorType: "status_code",
		URL: "https://www.autofrage.net/nutzer/%s",
		URLMain: "https://www.autofrage.net/",
		UsernameClaimed: "autofrage",
	},
	"Cryptomator Forum": {
		ErrorType: "status_code",
		URL: "https://community.cryptomator.org/u/%s",
		URLMain: "https://community.cryptomator.org/",
		UsernameClaimed: "michael",
	},
	"EyeEm": {
		ErrorType: "status_code",
		URL: "https://www.eyeem.com/u/%s",
		URLMain: "https://www.eyeem.com/",
		UsernameClaimed: "blue",
	},
	"Football": {
		ErrorMsg: []string{
			"Пользователь с таким именем не найден",
		},
		ErrorType: "message",
		URL: "https://www.rusfootball.info/user/%s/",
		URLMain: "https://www.rusfootball.info/",
		UsernameClaimed: "solo87",
	},
	"FortniteTracker": {
		ErrorType: "status_code",
		URL: "https://fortnitetracker.com/profile/all/%s",
		URLMain: "https://fortnitetracker.com/challenges",
		UsernameClaimed: "blue",
	},
	"Gesundheitsfrage": {
		ErrorType: "status_code",
		URL: "https://www.gesundheitsfrage.net/nutzer/%s",
		URLMain: "https://www.gesundheitsfrage.net/",
		UsernameClaimed: "gutefrage",
	},
	"SoundCloud": {
		ErrorType: "status_code",
		URL: "https://soundcloud.com/%s",
		URLMain: "https://soundcloud.com/",
		UsernameClaimed: "blue",
	},
	"CTAN": {
		ErrorType: "status_code",
		URL: "https://ctan.org/author/%s",
		URLMain: "https://ctan.org/",
		UsernameClaimed: "briggs",
	},
	"Codechef": {
		ErrorType: "response_url",
		URL: "https://www.codechef.com/users/%s",
		URLMain: "https://www.codechef.com/",
		UsernameClaimed: "blue",
		ErrorURL: "https://www.codechef.com/",
	},
	"NationStates Nation": {
		ErrorMsg: []string{
			"Was this your nation? It may have ceased to exist due to inactivity, but can rise again!",
		},
		ErrorType: "message",
		URL: "https://nationstates.net/nation=%s",
		URLMain: "https://nationstates.net",
		UsernameClaimed: "the_holy_principality_of_saint_mark",
	},
	"Pastebin": {
		ErrorMsg: []string{
			"Not Found (#404)",
		},
		ErrorType: "message",
		URL: "https://pastebin.com/u/%s",
		URLMain: "https://pastebin.com/",
		UsernameClaimed: "blue",
	},
	"Speedrun.com": {
		ErrorType: "status_code",
		URL: "https://speedrun.com/users/%s",
		URLMain: "https://speedrun.com/",
		UsernameClaimed: "example",
	},
	"Steam Community (Group)": {
		ErrorMsg: []string{
			"No group could be retrieved for the given URL",
		},
		ErrorType: "message",
		URL: "https://steamcommunity.com/groups/%s",
		URLMain: "https://steamcommunity.com/",
		UsernameClaimed: "blue",
	},
	"TryHackMe": {
		ErrorMsg: []string{
			"{\"success\":false}",
		},
		ErrorType: "message",
		RegexCheck: "^[a-zA-Z0-9.]{1,16}$",
		URL: "https://tryhackme.com/p/%s",
		URLMain: "https://tryhackme.com/",
		URLProbe: "https://tryhackme.com/api/user/exist/%s",
		UsernameClaimed: "ashu",
	},
	"pikabu": {
		ErrorType: "status_code",
		URL: "https://pikabu.ru/@%s",
		URLMain: "https://pikabu.ru/",
		UsernameClaimed: "blue",
	},
	"BOOTH": {
		ErrorType: "response_url",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.booth.pm/",
		URLMain: "https://booth.pm/",
		UsernameClaimed: "blue",
		ErrorURL: "https://booth.pm/",
	},
	"Clozemaster": {
		ErrorMsg: []string{
			"Oh no! Player not found.",
		},
		ErrorType: "message",
		URL: "https://www.clozemaster.com/players/%s",
		URLMain: "https://www.clozemaster.com",
		UsernameClaimed: "green",
	},
	"ColourLovers": {
		ErrorType: "status_code",
		URL: "https://www.colourlovers.com/lover/%s",
		URLMain: "https://www.colourlovers.com/",
		UsernameClaimed: "blue",
	},
	"Finanzfrage": {
		ErrorType: "status_code",
		URL: "https://www.finanzfrage.net/nutzer/%s",
		URLMain: "https://www.finanzfrage.net/",
		UsernameClaimed: "finanzfrage",
	},
	"moikrug": {
		ErrorType: "status_code",
		URL: "https://moikrug.ru/%s",
		URLMain: "https://moikrug.ru/",
		UsernameClaimed: "blue",
	},
	"mstdn.io": {
		ErrorType: "status_code",
		URL: "https://mstdn.io/@%s",
		URLMain: "https://mstdn.io/",
		UsernameClaimed: "blue",
	},
	"nairaland.com": {
		ErrorType: "status_code",
		URL: "https://www.nairaland.com/%s",
		URLMain: "https://www.nairaland.com/",
		UsernameClaimed: "red",
	},
	"Avizo": {
		ErrorType: "response_url",
		URL: "https://www.avizo.cz/%s/",
		URLMain: "https://www.avizo.cz/",
		UsernameClaimed: "blue",
		ErrorURL: "https://www.avizo.cz/",
	},
	"NationStates Region": {
		ErrorMsg: []string{
			"does not exist.",
		},
		ErrorType: "message",
		URL: "https://nationstates.net/region=%s",
		URLMain: "https://nationstates.net",
		UsernameClaimed: "the_west_pacific",
	},
	"SoylentNews": {
		ErrorMsg: []string{
			"The user you requested does not exist, no matter how much you wish this might be the case.",
		},
		ErrorType: "message",
		URL: "https://soylentnews.org/~%s",
		URLMain: "https://soylentnews.org",
		UsernameClaimed: "adam",
	},
	"Gamespot": {
		ErrorType: "status_code",
		URL: "https://www.gamespot.com/profile/%s/",
		URLMain: "https://www.gamespot.com/",
		UsernameClaimed: "blue",
	},
	"HackenProof (Hackers)": {
		ErrorMsg: []string{
			"Page not found",
		},
		ErrorType: "message",
		RegexCheck: "^[\\w-]{,34}$",
		URL: "https://hackenproof.com/hackers/%s",
		URLMain: "https://hackenproof.com/",
		UsernameClaimed: "blazezaria",
	},
	"Kongregate": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://www.kongregate.com/accounts/%s",
		URLMain: "https://www.kongregate.com/",
		UsernameClaimed: "blue",
		Headers: map[string]string{
			"Accept": "text/html",
		},
	},
	"Pornhub": {
		ErrorType: "status_code",
		URL: "https://pornhub.com/users/%s",
		URLMain: "https://pornhub.com/",
		UsernameClaimed: "blue",
		IsNSFW: true,
	},
	"GitBook": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.gitbook.io/",
		URLMain: "https://gitbook.com/",
		UsernameClaimed: "gitbook",
	},
	"fixya": {
		ErrorType: "status_code",
		URL: "https://www.fixya.com/users/%s",
		URLMain: "https://www.fixya.com",
		UsernameClaimed: "adam",
	},
	"Cracked": {
		ErrorType: "response_url",
		URL: "https://www.cracked.com/members/%s/",
		URLMain: "https://www.cracked.com/",
		UsernameClaimed: "blue",
		ErrorURL: "https://www.cracked.com/",
	},
	"HudsonRock": {
		ErrorMsg: []string{
			"This username is not associated",
		},
		ErrorType: "message",
		URL: "https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-username?username=%s",
		URLMain: "https://hudsonrock.com",
		UsernameClaimed: "testadmin",
	},
	"PromoDJ": {
		ErrorType: "status_code",
		URL: "http://promodj.com/%s",
		URLMain: "http://promodj.com/",
		UsernameClaimed: "blue",
	},
	"Rajce.net": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.rajce.idnes.cz/",
		URLMain: "https://www.rajce.idnes.cz/",
		UsernameClaimed: "blue",
	},
	"Replit.com": {
		ErrorType: "status_code",
		URL: "https://replit.com/@%s",
		URLMain: "https://replit.com/",
		UsernameClaimed: "blue",
	},
	"TRAKTRAIN": {
		ErrorType: "status_code",
		URL: "https://traktrain.com/%s",
		URLMain: "https://traktrain.com/",
		UsernameClaimed: "traktrain",
	},
	"Tenor": {
		ErrorType: "status_code",
		RegexCheck: "^[A-Za-z0-9_]{2,32}$",
		URL: "https://tenor.com/users/%s",
		URLMain: "https://tenor.com/",
		UsernameClaimed: "red",
	},
	"Wikipedia": {
		ErrorMsg: []string{
			"centralauth-admin-nonexistent:",
		},
		ErrorType: "message",
		URL: "https://en.wikipedia.org/wiki/Special:CentralAuth/%s?uselang=qqx",
		URLMain: "https://www.wikipedia.org/",
		UsernameClaimed: "Hoadlck",
	},
	"DigitalSpy": {
		ErrorMsg: []string{
			"The page you were looking for could not be found.",
		},
		ErrorType: "message",
		RegexCheck: "^\\w{3,20}$",
		URL: "https://forums.digitalspy.com/profile/%s",
		URLMain: "https://forums.digitalspy.com/",
		UsernameClaimed: "blue",
	},
	"Flickr": {
		ErrorType: "status_code",
		URL: "https://www.flickr.com/people/%s",
		URLMain: "https://www.flickr.com/",
		UsernameClaimed: "blue",
	},
	"Heavy-R": {
		ErrorMsg: []string{
			"Channel not found",
		},
		ErrorType: "message",
		URL: "https://www.heavy-r.com/user/%s",
		URLMain: "https://www.heavy-r.com/",
		UsernameClaimed: "kilroy222",
		IsNSFW: true,
	},
	"NintendoLife": {
		ErrorType: "status_code",
		URL: "https://www.nintendolife.com/users/%s",
		URLMain: "https://www.nintendolife.com/",
		UsernameClaimed: "goku",
	},
	"kaskus": {
		ErrorType: "status_code",
		URL: "https://www.kaskus.co.id/@%s",
		URLMain: "https://www.kaskus.co.id/",
		UsernameClaimed: "l0mbart",
	},
	"Ninja Kiwi": {
		ErrorType: "response_url",
		URL: "https://ninjakiwi.com/profile/%s",
		URLMain: "https://ninjakiwi.com/",
		UsernameClaimed: "Kyruko",
		ErrorURL: "https://ninjakiwi.com/profile/%s",
	},
	"Tiendanube": {
		ErrorType: "status_code",
		URL: "https://%s.mitiendanube.com/",
		URLMain: "https://www.tiendanube.com/",
		UsernameClaimed: "blue",
	},
	"Trakt": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*$",
		URL: "https://www.trakt.tv/users/%s",
		URLMain: "https://www.trakt.tv/",
		UsernameClaimed: "blue",
	},
	"furaffinity": {
		ErrorMsg: []string{
			"This user cannot be found.",
		},
		ErrorType: "message",
		URL: "https://www.furaffinity.net/user/%s",
		URLMain: "https://www.furaffinity.net",
		UsernameClaimed: "jesus",
	},
	"threads": {
		ErrorMsg: []string{
			"<title>Threads</title>",
		},
		ErrorType: "message",
		URL: "https://www.threads.net/@%s",
		URLMain: "https://www.threads.net/",
		UsernameClaimed: "zuck",
		Headers: map[string]string{
			"Sec-Fetch-Mode": "navigate",
		},
	},
	"Discogs": {
		ErrorType: "status_code",
		URL: "https://www.discogs.com/user/%s",
		URLMain: "https://www.discogs.com/",
		UsernameClaimed: "blue",
	},
	"Giant Bomb": {
		ErrorType: "status_code",
		URL: "https://www.giantbomb.com/profile/%s/",
		URLMain: "https://www.giantbomb.com/",
		UsernameClaimed: "bob",
	},
	"Instructables": {
		ErrorType: "status_code",
		URL: "https://www.instructables.com/member/%s",
		URLMain: "https://www.instructables.com/",
		URLProbe: "https://www.instructables.com/json-api/showAuthorExists?screenName=%s",
		UsernameClaimed: "blue",
	},
	"Slant": {
		ErrorType: "status_code",
		RegexCheck: "^.{2,32}$",
		URL: "https://www.slant.co/users/%s",
		URLMain: "https://www.slant.co/",
		UsernameClaimed: "blue",
	},
	"Steam Community (User)": {
		ErrorMsg: []string{
			"The specified profile could not be found",
		},
		ErrorType: "message",
		URL: "https://steamcommunity.com/id/%s/",
		URLMain: "https://steamcommunity.com/",
		UsernameClaimed: "blue",
	},
	"Tellonym.me": {
		ErrorType: "status_code",
		URL: "https://tellonym.me/%s",
		URLMain: "https://tellonym.me/",
		UsernameClaimed: "blue",
	},
	"pr0gramm": {
		ErrorType: "status_code",
		URL: "https://pr0gramm.com/user/%s",
		URLMain: "https://pr0gramm.com/",
		URLProbe: "https://pr0gramm.com/api/profile/info?name=%s",
		UsernameClaimed: "cha0s",
	},
	"Erome": {
		ErrorType: "status_code",
		URL: "https://www.erome.com/%s",
		URLMain: "https://www.erome.com/",
		UsernameClaimed: "bob",
		IsNSFW: true,
	},
	"Grailed": {
		ErrorType: "response_url",
		URL: "https://www.grailed.com/%s",
		URLMain: "https://www.grailed.com/",
		UsernameClaimed: "blue",
		ErrorURL: "https://www.grailed.com/%s",
	},
	"Newgrounds": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://%s.newgrounds.com",
		URLMain: "https://newgrounds.com",
		UsernameClaimed: "blue",
	},
	"Scratch": {
		ErrorType: "status_code",
		URL: "https://scratch.mit.edu/users/%s",
		URLMain: "https://scratch.mit.edu/",
		UsernameClaimed: "griffpatch",
	},
	"Spotify": {
		ErrorType: "status_code",
		URL: "https://open.spotify.com/user/%s",
		URLMain: "https://open.spotify.com/",
		UsernameClaimed: "blue",
	},
	"d3RU": {
		ErrorType: "status_code",
		URL: "https://d3.ru/user/%s/posts",
		URLMain: "https://d3.ru/",
		UsernameClaimed: "blue",
	},
	"phpRU": {
		ErrorMsg: []string{
			"Указанный пользователь не найден. Пожалуйста, введите другое имя.",
		},
		ErrorType: "message",
		URL: "https://php.ru/forum/members/?username=%s",
		URLMain: "https://php.ru/forum/",
		UsernameClaimed: "apple",
	},
	"AllMyLinks": {
		ErrorMsg: []string{
			"Not Found",
		},
		ErrorType: "message",
		RegexCheck: "^[a-z0-9][a-z0-9-]{2,32}$",
		URL: "https://allmylinks.com/%s",
		URLMain: "https://allmylinks.com/",
		UsernameClaimed: "blue",
	},
	"PlayStore": {
		ErrorType: "status_code",
		URL: "https://play.google.com/store/apps/developer?id=%s",
		URLMain: "https://play.google.com/store",
		UsernameClaimed: "Facebook",
	},
	"SublimeForum": {
		ErrorType: "status_code",
		URL: "https://forum.sublimetext.com/u/%s",
		URLMain: "https://forum.sublimetext.com/",
		UsernameClaimed: "blue",
	},
	"Trello": {
		ErrorMsg: []string{
			"model not found",
		},
		ErrorType: "message",
		URL: "https://trello.com/%s",
		URLMain: "https://trello.com/",
		URLProbe: "https://trello.com/1/Members/%s",
		UsernameClaimed: "blue",
	},
	"WICG Forum": {
		ErrorType: "status_code",
		RegexCheck: "^(?![.-])[a-zA-Z0-9_.-]{3,20}$",
		URL: "https://discourse.wicg.io/u/%s/summary",
		URLMain: "https://discourse.wicg.io/",
		UsernameClaimed: "stefano",
	},
	"eGPU": {
		ErrorType: "status_code",
		URL: "https://egpu.io/forums/profile/%s/",
		URLMain: "https://egpu.io/",
		UsernameClaimed: "blue",
	},
	"kwork": {
		ErrorType: "status_code",
		URL: "https://kwork.ru/user/%s",
		URLMain: "https://www.kwork.ru/",
		UsernameClaimed: "blue",
	},
	"Bitwarden Forum": {
		ErrorType: "status_code",
		RegexCheck: "^(?![.-])[a-zA-Z0-9_.-]{3,20}$",
		URL: "https://community.bitwarden.com/u/%s/summary",
		URLMain: "https://bitwarden.com/",
		UsernameClaimed: "blue",
	},
	"Crevado": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.crevado.com",
		URLMain: "https://crevado.com/",
		UsernameClaimed: "blue",
	},
	"DailyMotion": {
		ErrorType: "status_code",
		URL: "https://www.dailymotion.com/%s",
		URLMain: "https://www.dailymotion.com/",
		UsernameClaimed: "blue",
	},
	"Hugging Face": {
		ErrorType: "status_code",
		URL: "https://huggingface.co/%s",
		URLMain: "https://huggingface.co/",
		UsernameClaimed: "Pasanlaksitha",
	},
	"PepperIT": {
		ErrorMsg: []string{
			"La pagina che hai provato a raggiungere non si trova qui",
		},
		ErrorType: "message",
		URL: "https://www.pepper.it/profile/%s/overview",
		URLMain: "https://www.pepper.it",
		UsernameClaimed: "asoluinostrisca",
	},
	"Sketchfab": {
		ErrorType: "status_code",
		URL: "https://sketchfab.com/%s",
		URLMain: "https://sketchfab.com/",
		UsernameClaimed: "blue",
	},
	"opennet": {
		ErrorMsg: []string{
			"Имя участника не найдено",
		},
		ErrorType: "message",
		RegexCheck: "^[^-]*$",
		URL: "https://www.opennet.ru/~%s",
		URLMain: "https://www.opennet.ru/",
		UsernameClaimed: "anonismus",
	},
	"Apple Developer": {
		ErrorType: "status_code",
		URL: "https://developer.apple.com/forums/profile/%s",
		URLMain: "https://developer.apple.com",
		UsernameClaimed: "lio24d",
	},
	"GitLab": {
		ErrorMsg: []string{
			"[]",
		},
		ErrorType: "message",
		URL: "https://gitlab.com/%s",
		URLMain: "https://gitlab.com/",
		URLProbe: "https://gitlab.com/api/v4/users?username=%s",
		UsernameClaimed: "blue",
	},
	"Monkeytype": {
		ErrorType: "status_code",
		URL: "https://monkeytype.com/profile/%s",
		URLMain: "https://monkeytype.com/",
		URLProbe: "https://api.monkeytype.com/users/%s/profile",
		UsernameClaimed: "Lost_Arrow",
	},
	"MyAnimeList": {
		ErrorType: "status_code",
		URL: "https://myanimelist.net/profile/%s",
		URLMain: "https://myanimelist.net/",
		UsernameClaimed: "blue",
	},
	"Wix": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.wix.com",
		URLMain: "https://wix.com/",
		UsernameClaimed: "support",
	},
	"BuyMeACoffee": {
		ErrorType: "status_code",
		RegexCheck: "[a-zA-Z0-9]{3,15}",
		URL: "https://buymeacoff.ee/%s",
		URLMain: "https://www.buymeacoffee.com/",
		URLProbe: "https://www.buymeacoffee.com/%s",
		UsernameClaimed: "red",
	},
	"Clapper": {
		ErrorType: "status_code",
		URL: "https://clapperapp.com/%s",
		URLMain: "https://clapperapp.com/",
		UsernameClaimed: "blue",
	},
	"Memrise": {
		ErrorType: "status_code",
		URL: "https://www.memrise.com/user/%s/",
		URLMain: "https://www.memrise.com/",
		UsernameClaimed: "blue",
	},
	"Myspace": {
		ErrorType: "status_code",
		URL: "https://myspace.com/%s",
		URLMain: "https://myspace.com/",
		UsernameClaimed: "blue",
	},
	"Polarsteps": {
		ErrorType: "status_code",
		URL: "https://polarsteps.com/%s",
		URLMain: "https://polarsteps.com/",
		URLProbe: "https://api.polarsteps.com/users/byusername/%s",
		UsernameClaimed: "james",
	},
	"Rclone Forum": {
		ErrorType: "status_code",
		URL: "https://forum.rclone.org/u/%s",
		URLMain: "https://forum.rclone.org/",
		UsernameClaimed: "ncw",
	},
	"Strava": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*?$",
		URL: "https://www.strava.com/athletes/%s",
		URLMain: "https://www.strava.com/",
		UsernameClaimed: "blue",
	},
	"Twitter": {
		ErrorMsg: []string{
			"<div class=\"error-panel\"><span>User ",
			"<title>429 Too Many Requests</title>",
		},
		ErrorType: "message",
		RegexCheck: "^[a-zA-Z0-9_]{1,15}$",
		URL: "https://x.com/%s",
		URLMain: "https://x.com/",
		URLProbe: "https://nitter.privacydev.net/%s",
		UsernameClaimed: "blue",
	},
	"2Dimensions": {
		ErrorType: "status_code",
		URL: "https://2Dimensions.com/a/%s",
		URLMain: "https://2Dimensions.com/",
		UsernameClaimed: "blue",
	},
	"AdmireMe.Vip": {
		ErrorMsg: []string{
			"Page Not Found",
		},
		ErrorType: "message",
		URL: "https://admireme.vip/%s",
		URLMain: "https://admireme.vip/",
		UsernameClaimed: "DemiDevil",
		IsNSFW: true,
	},
	"CyberDefenders": {
		ErrorMsg: []string{
			"<title>Blue Team Training for SOC analysts and DFIR - CyberDefenders</title>",
		},
		ErrorType: "message",
		RegexCheck: "^[^\\/:*?\"<>|@]{3,50}$",
		URL: "https://cyberdefenders.org/p/%s",
		URLMain: "https://cyberdefenders.org/",
		UsernameClaimed: "mlohn",
		RequestMethod: "GET",
	},
	"Slashdot": {
		ErrorMsg: []string{
			"user you requested does not exist",
		},
		ErrorType: "message",
		URL: "https://slashdot.org/~%s",
		URLMain: "https://slashdot.org",
		UsernameClaimed: "blue",
	},
	"note": {
		ErrorType: "status_code",
		URL: "https://note.com/%s",
		URLMain: "https://note.com/",
		UsernameClaimed: "blue",
	},
	"Anilist": {
		ErrorType: "status_code",
		RegexCheck: "^[A-Za-z0-9]{2,20}$",
		URL: "https://anilist.co/user/%s/",
		URLMain: "https://anilist.co/",
		URLProbe: "https://graphql.anilist.co/",
		UsernameClaimed: "Josh",
		RequestMethod: "POST",
		RequestPayload: "{\"query\":\"query($name:String){User(name:$name){id}}\",\"variables\":{\"name\":\"%s\"}}",
	},
	"CloudflareCommunity": {
		ErrorType: "status_code",
		URL: "https://community.cloudflare.com/u/%s",
		URLMain: "https://community.cloudflare.com/",
		UsernameClaimed: "blue",
	},
	"DMOJ": {
		ErrorMsg: []string{
			"No such user",
		},
		ErrorType: "message",
		URL: "https://dmoj.ca/user/%s",
		URLMain: "https://dmoj.ca/",
		UsernameClaimed: "junferno",
	},
	"LessWrong": {
		ErrorType: "status_code",
		URL: "https://www.lesswrong.com/users/@%s",
		URLMain: "https://www.lesswrong.com/",
		UsernameClaimed: "blue",
	},
	"RoyalCams": {
		ErrorType: "status_code",
		URL: "https://royalcams.com/profile/%s",
		URLMain: "https://royalcams.com",
		UsernameClaimed: "asuna-,black",
	},
	"7Cups": {
		ErrorType: "status_code",
		URL: "https://www.7cups.com/@%s",
		URLMain: "https://www.7cups.com/",
		UsernameClaimed: "blue",
	},
	"Behance": {
		ErrorType: "status_code",
		URL: "https://www.behance.net/%s",
		URLMain: "https://www.behance.net/",
		UsernameClaimed: "blue",
	},
	"Genius (Artists)": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9]{5,50}$",
		URL: "https://genius.com/artists/%s",
		URLMain: "https://genius.com/",
		UsernameClaimed: "genius",
	},
	"Hubski": {
		ErrorMsg: []string{
			"No such user",
		},
		ErrorType: "message",
		URL: "https://hubski.com/user/%s",
		URLMain: "https://hubski.com/",
		UsernameClaimed: "blue",
	},
	"Splice": {
		ErrorType: "status_code",
		URL: "https://splice.com/%s",
		URLMain: "https://splice.com/",
		UsernameClaimed: "splice",
	},
	"VLR": {
		ErrorType: "status_code",
		URL: "https://www.vlr.gg/user/%s",
		URLMain: "https://www.vlr.gg",
		UsernameClaimed: "optms",
	},
	"YouNow": {
		ErrorMsg: []string{
			"No users found",
		},
		ErrorType: "message",
		URL: "https://www.younow.com/%s/",
		URLMain: "https://www.younow.com/",
		URLProbe: "https://api.younow.com/php/api/broadcast/info/user=%s/",
		UsernameClaimed: "blue",
	},
	"couchsurfing": {
		ErrorType: "status_code",
		URL: "https://www.couchsurfing.com/people/%s",
		URLMain: "https://www.couchsurfing.com/",
		UsernameClaimed: "blue",
	},
	"All Things Worn": {
		ErrorMsg: []string{
			"Sell Used Panties",
		},
		ErrorType: "message",
		URL: "https://www.allthingsworn.com/profile/%s",
		URLMain: "https://www.allthingsworn.com",
		UsernameClaimed: "pink",
		IsNSFW: true,
	},
	"Chatujme.cz": {
		ErrorMsg: []string{
			"Neexistujicí profil",
		},
		ErrorType: "message",
		RegexCheck: "^[a-zA-Z][a-zA-Z1-9_-]*$",
		URL: "https://profil.chatujme.cz/%s",
		URLMain: "https://chatujme.cz/",
		UsernameClaimed: "david",
	},
	"Gitea": {
		ErrorType: "status_code",
		URL: "https://gitea.com/%s",
		URLMain: "https://gitea.com/",
		UsernameClaimed: "xorm",
	},
	"LiveJournal": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://%s.livejournal.com",
		URLMain: "https://www.livejournal.com/",
		UsernameClaimed: "blue",
	},
	"MyMiniFactory": {
		ErrorType: "status_code",
		URL: "https://www.myminifactory.com/users/%s",
		URLMain: "https://www.myminifactory.com/",
		UsernameClaimed: "blue",
	},
	"RedTube": {
		ErrorType: "status_code",
		URL: "https://www.redtube.com/users/%s",
		URLMain: "https://www.redtube.com/",
		UsernameClaimed: "hacker",
		IsNSFW: true,
	},
	"ReverbNation": {
		ErrorMsg: []string{
			"Sorry, we couldn't find that page",
		},
		ErrorType: "message",
		URL: "https://www.reverbnation.com/%s",
		URLMain: "https://www.reverbnation.com/",
		UsernameClaimed: "blue",
	},
	"SourceForge": {
		ErrorType: "status_code",
		URL: "https://sourceforge.net/u/%s",
		URLMain: "https://sourceforge.net/",
		UsernameClaimed: "blue",
	},
	"Atcoder": {
		ErrorType: "status_code",
		URL: "https://atcoder.jp/users/%s",
		URLMain: "https://atcoder.jp/",
		UsernameClaimed: "ksun48",
	},
	"Carbonmade": {
		ErrorType: "response_url",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.carbonmade.com",
		URLMain: "https://carbonmade.com/",
		UsernameClaimed: "jenny",
		ErrorURL: "https://carbonmade.com/fourohfour?domain=%s.carbonmade.com",
	},
	"Flipboard": {
		ErrorType: "status_code",
		RegexCheck: "^([a-zA-Z0-9_]){1,15}$",
		URL: "https://flipboard.com/@%s",
		URLMain: "https://flipboard.com/",
		UsernameClaimed: "blue",
	},
	"RocketTube": {
		ErrorMsg: []string{
			"OOPS! Houston, we have a problem",
		},
		ErrorType: "message",
		URL: "https://www.rockettube.com/%s",
		URLMain: "https://www.rockettube.com/",
		UsernameClaimed: "Tatteddick5600",
		IsNSFW: true,
	},
	"TradingView": {
		ErrorType: "status_code",
		URL: "https://www.tradingview.com/u/%s/",
		URLMain: "https://www.tradingview.com/",
		UsernameClaimed: "blue",
		RequestMethod: "GET",
	},
	"Venmo": {
		ErrorMsg: []string{
			"Venmo | Page Not Found",
		},
		ErrorType: "message",
		URL: "https://account.venmo.com/u/%s",
		URLMain: "https://venmo.com/",
		URLProbe: "https://test1.venmo.com/u/%s",
		UsernameClaimed: "jenny",
		Headers: map[string]string{
			"Host": "account.venmo.com",
		},
	},
	"YouTube": {
		ErrorType: "status_code",
		URL: "https://www.youtube.com/@%s",
		URLMain: "https://www.youtube.com/",
		UsernameClaimed: "youtube",
	},
	"hunting": {
		ErrorMsg: []string{
			"Указанный пользователь не найден. Пожалуйста, введите другое имя.",
		},
		ErrorType: "message",
		URL: "https://www.hunting.ru/forum/members/?username=%s",
		URLMain: "https://www.hunting.ru/forum/",
		UsernameClaimed: "red",
	},
	"Codeforces": {
		ErrorType: "status_code",
		URL: "https://codeforces.com/profile/%s",
		URLMain: "https://codeforces.com/",
		URLProbe: "https://codeforces.com/api/user.info?handles=%s",
		UsernameClaimed: "tourist",
	},
	"Letterboxd": {
		ErrorMsg: []string{
			"Sorry, we can’t find the page you’ve requested.",
		},
		ErrorType: "message",
		URL: "https://letterboxd.com/%s",
		URLMain: "https://letterboxd.com/",
		UsernameClaimed: "blue",
	},
	"LinkedIn": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9]{3,100}$",
		URL: "https://linkedin.com/in/%s",
		URLMain: "https://linkedin.com",
		UsernameClaimed: "paulpfeister",
		RequestMethod: "GET",
	},
	"Ultimate-Guitar": {
		ErrorType: "status_code",
		URL: "https://ultimate-guitar.com/u/%s",
		URLMain: "https://ultimate-guitar.com/",
		UsernameClaimed: "blue",
	},
	"interpals": {
		ErrorMsg: []string{
			"The requested user does not exist or is inactive",
		},
		ErrorType: "message",
		URL: "https://www.interpals.net/%s",
		URLMain: "https://www.interpals.net/",
		UsernameClaimed: "blue",
	},
	"Giphy": {
		ErrorMsg: []string{
			"<title> GIFs - Find &amp; Share on GIPHY</title>",
		},
		ErrorType: "message",
		URL: "https://giphy.com/%s",
		URLMain: "https://giphy.com/",
		UsernameClaimed: "red",
	},
	"Google Play": {
		ErrorMsg: []string{
			"the requested URL was not found on this server",
		},
		ErrorType: "message",
		URL: "https://play.google.com/store/apps/developer?id=%s",
		URLMain: "https://play.google.com",
		UsernameClaimed: "GitHub",
	},
	"Motorradfrage": {
		ErrorType: "status_code",
		URL: "https://www.motorradfrage.net/nutzer/%s",
		URLMain: "https://www.motorradfrage.net/",
		UsernameClaimed: "gutefrage",
	},
	"Opensource": {
		ErrorType: "status_code",
		URL: "https://opensource.com/users/%s",
		URLMain: "https://opensource.com/",
		UsernameClaimed: "red",
	},
	"Unsplash": {
		ErrorType: "status_code",
		RegexCheck: "^[a-z0-9_]{1,60}$",
		URL: "https://unsplash.com/@%s",
		URLMain: "https://unsplash.com/",
		UsernameClaimed: "jenny",
	},
	"igromania": {
		ErrorMsg: []string{
			"Пользователь не зарегистрирован и не имеет профиля для просмотра.",
		},
		ErrorType: "message",
		URL: "http://forum.igromania.ru/member.php?username=%s",
		URLMain: "http://forum.igromania.ru/",
		UsernameClaimed: "blue",
	},
	"jbzd.com.pl": {
		ErrorType: "status_code",
		URL: "https://jbzd.com.pl/uzytkownik/%s",
		URLMain: "https://jbzd.com.pl/",
		UsernameClaimed: "blue",
	},
	"Choice Community": {
		ErrorType: "status_code",
		URL: "https://choice.community/u/%s/summary",
		URLMain: "https://choice.community/",
		UsernameClaimed: "gordon",
	},
	"Codewars": {
		ErrorType: "status_code",
		URL: "https://www.codewars.com/users/%s",
		URLMain: "https://www.codewars.com",
		UsernameClaimed: "example",
	},
	"Duolingo": {
		ErrorMsg: []string{
			"{\"users\":[]}",
		},
		ErrorType: "message",
		URL: "https://www.duolingo.com/profile/%s",
		URLMain: "https://duolingo.com/",
		URLProbe: "https://www.duolingo.com/2017-06-30/users?username=%s",
		UsernameClaimed: "blue",
	},
	"Launchpad": {
		ErrorType: "status_code",
		URL: "https://launchpad.net/~%s",
		URLMain: "https://launchpad.net/",
		UsernameClaimed: "blue",
	},
	"Rarible": {
		ErrorType: "status_code",
		URL: "https://rarible.com/marketplace/api/v4/urls/%s",
		URLMain: "https://rarible.com/",
		UsernameClaimed: "blue",
	},
	"Slack": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://%s.slack.com",
		URLMain: "https://slack.com",
		UsernameClaimed: "blue",
	},
	"Fanpop": {
		ErrorType: "response_url",
		URL: "https://www.fanpop.com/fans/%s",
		URLMain: "https://www.fanpop.com/",
		UsernameClaimed: "blue",
		ErrorURL: "https://www.fanpop.com/",
	},
	"Polygon": {
		ErrorType: "status_code",
		URL: "https://www.polygon.com/users/%s",
		URLMain: "https://www.polygon.com/",
		UsernameClaimed: "swiftstickler",
	},
	"PyPi": {
		ErrorType: "status_code",
		URL: "https://pypi.org/user/%s",
		URLMain: "https://pypi.org",
		URLProbe: "https://pypi.org/_includes/administer-user-include/%s",
		UsernameClaimed: "Blue",
	},
	"Weebly": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9-]{1,63}$",
		URL: "https://%s.weebly.com/",
		URLMain: "https://weebly.com/",
		UsernameClaimed: "blue",
	},
	"WolframalphaForum": {
		ErrorType: "status_code",
		URL: "https://community.wolfram.com/web/%s/home",
		URLMain: "https://community.wolfram.com/",
		UsernameClaimed: "unico",
	},
	"minds": {
		ErrorMsg: []string{
			"\"valid\":true",
		},
		ErrorType: "message",
		URL: "https://www.minds.com/%s/",
		URLMain: "https://www.minds.com",
		URLProbe: "https://www.minds.com/api/v3/register/validate?username=%s",
		UsernameClaimed: "john",
	},
	"Dribbble": {
		ErrorMsg: []string{
			"Whoops, that page is gone.",
		},
		ErrorType: "message",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://dribbble.com/%s",
		URLMain: "https://dribbble.com/",
		UsernameClaimed: "blue",
	},
	"Empretienda AR": {
		ErrorType: "status_code",
		URL: "https://%s.empretienda.com.ar",
		URLMain: "https://empretienda.com",
		UsernameClaimed: "camalote",
	},
	"sessionize": {
		ErrorType: "status_code",
		URL: "https://sessionize.com/%s",
		URLMain: "https://sessionize.com/",
		UsernameClaimed: "jason-,mayes",
	},
	"Keybase": {
		ErrorType: "status_code",
		URL: "https://keybase.io/%s",
		URLMain: "https://keybase.io/",
		UsernameClaimed: "blue",
	},
	"Topcoder": {
		ErrorType: "status_code",
		RegexCheck: "[a-zA-Z0-9 ]",
		URL: "https://profiles.topcoder.com/%s/",
		URLMain: "https://topcoder.com/",
		URLProbe: "https://api.topcoder.com/v5/members/%s",
		UsernameClaimed: "USER",
	},
	"Typeracer": {
		ErrorMsg: []string{
			"Profile Not Found",
		},
		ErrorType: "message",
		URL: "https://data.typeracer.com/pit/profile?user=%s",
		URLMain: "https://typeracer.com",
		UsernameClaimed: "blue",
	},
	"Weblate": {
		ErrorType: "status_code",
		RegexCheck: "^[a-zA-Z0-9@._-]{1,150}$",
		URL: "https://hosted.weblate.org/user/%s/",
		URLMain: "https://hosted.weblate.org/",
		UsernameClaimed: "adam",
	},
	"omg.lol": {
		ErrorMsg: []string{
			"\"available\": true",
		},
		ErrorType: "message",
		URL: "https://%s.omg.lol",
		URLMain: "https://home.omg.lol",
		URLProbe: "https://api.omg.lol/address/%s/availability",
		UsernameClaimed: "adam",
	},
	"Career.habr": {
		ErrorMsg: []string{
			"<h1>Ошибка 404</h1>",
		},
		ErrorType: "message",
		URL: "https://career.habr.com/%s",
		URLMain: "https://career.habr.com/",
		UsernameClaimed: "blue",
	},
	"Fameswap": {
		ErrorType: "status_code",
		URL: "https://fameswap.com/user/%s",
		URLMain: "https://fameswap.com/",
		UsernameClaimed: "fameswap",
	},
	"HackerRank": {
		ErrorMsg: []string{
			"Something went wrong",
		},
		ErrorType: "message",
		RegexCheck: "^[^.]*?$",
		URL: "https://hackerrank.com/%s",
		URLMain: "https://hackerrank.com/",
		UsernameClaimed: "satznova",
	},
	"HubPages": {
		ErrorType: "status_code",
		URL: "https://hubpages.com/@%s",
		URLMain: "https://hubpages.com/",
		UsernameClaimed: "blue",
	},
	"Packagist": {
		ErrorType: "response_url",
		URL: "https://packagist.org/packages/%s/",
		URLMain: "https://packagist.org/",
		UsernameClaimed: "psr",
		ErrorURL: "https://packagist.org/search/?q=%s&reason=vendor_not_found",
	},
	"Xbox Gamertag": {
		ErrorType: "status_code",
		URL: "https://xboxgamertag.com/search/%s",
		URLMain: "https://xboxgamertag.com/",
		UsernameClaimed: "red",
	},
	"datingRU": {
		ErrorType: "status_code",
		URL: "http://dating.ru/%s",
		URLMain: "http://dating.ru",
		UsernameClaimed: "blue",
	},
	"habr": {
		ErrorType: "status_code",
		URL: "https://habr.com/ru/users/%s",
		URLMain: "https://habr.com/",
		UsernameClaimed: "blue",
	},
	"Chess": {
		ErrorMsg: []string{
			"Username is valid",
		},
		ErrorType: "message",
		RegexCheck: "^[a-z1-9]{3,25}$",
		URL: "https://www.chess.com/member/%s",
		URLMain: "https://www.chess.com/",
		URLProbe: "https://www.chess.com/callback/user/valid?username=%s",
		UsernameClaimed: "blue",
	},
	"Docker Hub": {
		ErrorType: "status_code",
		URL: "https://hub.docker.com/u/%s/",
		URLMain: "https://hub.docker.com/",
		URLProbe: "https://hub.docker.com/v2/users/%s/",
		UsernameClaimed: "blue",
	},
	"LOR": {
		ErrorType: "status_code",
		URL: "https://www.linux.org.ru/people/%s/profile",
		URLMain: "https://linux.org.ru/",
		UsernameClaimed: "red",
	},
	"Minecraft": {
		ErrorType: "status_code",
		URL: "https://api.mojang.com/users/profiles/minecraft/%s",
		URLMain: "https://minecraft.net/",
		UsernameClaimed: "blue",
		ErrorCode: 204,
	},
	"Telegram": {
		ErrorMsg: []string{
			"<title>Telegram Messenger</title>",
			"If you have <strong>Telegram</strong>, you can contact <a class=\"tgme_username_link\" href=\"tg://resolve?domain=",
		},
		ErrorType: "message",
		RegexCheck: "^[a-zA-Z0-9_]{3,32}[^_]$",
		URL: "https://t.me/%s",
		URLMain: "https://t.me/",
		UsernameClaimed: "blue",
	},
	"VSCO": {
		ErrorType: "status_code",
		URL: "https://vsco.co/%s",
		URLMain: "https://vsco.co/",
		UsernameClaimed: "blue",
	},
	"YouPic": {
		ErrorType: "status_code",
		URL: "https://youpic.com/photographer/%s/",
		URLMain: "https://youpic.com/",
		UsernameClaimed: "blue",
	},
	"last.fm": {
		ErrorType: "status_code",
		URL: "https://last.fm/user/%s",
		URLMain: "https://last.fm/",
		UsernameClaimed: "blue",
	},
	"Gitee": {
		ErrorType: "status_code",
		URL: "https://gitee.com/%s",
		URLMain: "https://gitee.com/",
		UsernameClaimed: "wizzer",
	},
	"SlideShare": {
		ErrorMsg: []string{
			"<title>Username available</title>",
		},
		ErrorType: "message",
		URL: "https://slideshare.net/%s",
		URLMain: "https://slideshare.net/",
		UsernameClaimed: "blue",
	},
	"mastodon.xyz": {
		ErrorType: "status_code",
		URL: "https://mastodon.xyz/@%s",
		URLMain: "https://mastodon.xyz/",
		UsernameClaimed: "TheKinrar",
	},
	"Motherless": {
		ErrorMsg: []string{
			"no longer a member",
		},
		ErrorType: "message",
		URL: "https://motherless.com/m/%s",
		URLMain: "https://motherless.com/",
		UsernameClaimed: "hacker",
		IsNSFW: true,
	},
	"CSSBattle": {
		ErrorType: "status_code",
		URL: "https://cssbattle.dev/player/%s",
		URLMain: "https://cssbattle.dev",
		UsernameClaimed: "beo",
	},
	"Codepen": {
		ErrorType: "status_code",
		URL: "https://codepen.io/%s",
		URLMain: "https://codepen.io/",
		UsernameClaimed: "blue",
	},
	"F3.cool": {
		ErrorType: "status_code",
		URL: "https://f3.cool/%s/",
		URLMain: "https://f3.cool/",
		UsernameClaimed: "blue",
	},
	"HackTheBox": {
		ErrorType: "status_code",
		URL: "https://forum.hackthebox.com/u/%s",
		URLMain: "https://forum.hackthebox.com/",
		UsernameClaimed: "angar",
	},
	"Reddit": {
		ErrorMsg: []string{
			"Sorry, nobody on Reddit goes by that name.",
		},
		ErrorType: "message",
		URL: "https://www.reddit.com/user/%s",
		URLMain: "https://www.reddit.com/",
		UsernameClaimed: "blue",
		Headers: map[string]string{
			"accept-language": "en-US,en;q=0.9",
		},
	},
	"ThemeForest": {
		ErrorType: "status_code",
		URL: "https://themeforest.net/user/%s",
		URLMain: "https://themeforest.net/",
		UsernameClaimed: "user",
	},
	"WordPressOrg": {
		ErrorType: "response_url",
		URL: "https://profiles.wordpress.org/%s/",
		URLMain: "https://wordpress.org/",
		UsernameClaimed: "blue",
		ErrorURL: "https://wordpress.org",
	},
	"Academia.edu": {
		ErrorType: "status_code",
		RegexCheck: "^[^.]*$",
		URL: "https://independent.academia.edu/%s",
		URLMain: "https://www.academia.edu/",
		UsernameClaimed: "blue",
	},
	"Dealabs": {
		ErrorMsg: []string{
			"La page que vous essayez",
		},
		ErrorType: "message",
		RegexCheck: "[a-z0-9]{4,16}",
		URL: "https://www.dealabs.com/profile/%s",
		URLMain: "https://www.dealabs.com/",
		UsernameClaimed: "blue",
	},
	"Gumroad": {
		ErrorMsg: []string{
			"Page not found (404) - Gumroad",
		},
		ErrorType: "message",
		RegexCheck: "^[^.]*?$",
		URL: "https://www.gumroad.com/%s",
		URLMain: "https://www.gumroad.com/",
		UsernameClaimed: "blue",
	},
	"LottieFiles": {
		ErrorType: "status_code",
		URL: "https://lottiefiles.com/%s",
		URLMain: "https://lottiefiles.com/",
		UsernameClaimed: "lottiefiles",
	},
	"Nightbot": {
		ErrorType: "status_code",
		URL: "https://nightbot.tv/t/%s/commands",
		URLMain: "https://nightbot.tv/",
		URLProbe: "https://api.nightbot.tv/1/channels/t/%s",
		UsernameClaimed: "green",
	},
	"Windy": {
		ErrorType: "status_code",
		URL: "https://community.windy.com/user/%s",
		URLMain: "https://windy.com/",
		UsernameClaimed: "blue",
	},
	"devRant": {
		ErrorType: "response_url",
		URL: "https://devrant.com/users/%s",
		URLMain: "https://devrant.com/",
		UsernameClaimed: "blue",
		ErrorURL: "https://devrant.com/",
	},
	"exophase": {
		ErrorType: "status_code",
		URL: "https://www.exophase.com/user/%s/",
		URLMain: "https://www.exophase.com/",
		UsernameClaimed: "blue",
	},
	"BugCrowd": {
		ErrorType: "status_code",
		URL: "https://bugcrowd.com/%s",
		URLMain: "https://bugcrowd.com/",
		UsernameClaimed: "ppfeister",
	},
	"Hashnode": {
		ErrorType: "status_code",
		URL: "https://hashnode.com/@%s",
		URLMain: "https://hashnode.com",
		UsernameClaimed: "blue",
	},
	"Intigriti": {
		ErrorType: "status_code",
		RegexCheck: "[a-z0-9_]{1,25}",
		URL: "https://app.intigriti.com/profile/%s",
		URLMain: "https://app.intigriti.com",
		URLProbe: "https://api.intigriti.com/user/public/profile/%s",
		UsernameClaimed: "blue",
		RequestMethod: "GET",
	},
	"NitroType": {
		ErrorMsg: []string{
			"<title>Nitro Type | Competitive Typing Game | Race Your Friends</title>",
		},
		ErrorType: "message",
		URL: "https://www.nitrotype.com/racer/%s",
		URLMain: "https://www.nitrotype.com/",
		UsernameClaimed: "jianclash",
	},
	"Nyaa.si": {
		ErrorType: "status_code",
		URL: "https://nyaa.si/user/%s",
		URLMain: "https://nyaa.si/",
		UsernameClaimed: "blue",
	},
	"Smule": {
		ErrorMsg: []string{
			"Smule | Page Not Found (404)",
		},
		ErrorType: "message",
		URL: "https://www.smule.com/%s",
		URLMain: "https://www.smule.com/",
		UsernameClaimed: "blue",
	},
	"freecodecamp": {
		ErrorType: "status_code",
		URL: "https://www.freecodecamp.org/%s",
		URLMain: "https://www.freecodecamp.org/",
		URLProbe: "https://api.freecodecamp.org/api/users/get-public-profile?username=%s",
		UsernameClaimed: "naveennamani",
	},
	"hackster": {
		ErrorType: "status_code",
		URL: "https://www.hackster.io/%s",
		URLMain: "https://www.hackster.io",
		UsernameClaimed: "blue",
	},
	"About.me": {
		ErrorType: "status_code",
		URL: "https://about.me/%s",
		URLMain: "https://about.me/",
		UsernameClaimed: "blue",
	},
	"Freelancer": {
		ErrorMsg: []string{
			"\"users\":%s",
		},
		ErrorType: "message",
		URL: "https://www.freelancer.com/u/%s",
		URLMain: "https://www.freelancer.com/",
		URLProbe: "https://www.freelancer.com/api/users/0.1/users?usernames%5B%5D=%s&compact=true",
		UsernameClaimed: "red0xff",
	},
	"Instagram": {
		ErrorType: "status_code",
		URL: "https://instagram.com/%s",
		URLMain: "https://instagram.com/",
		URLProbe: "https://imginn.com/%s",
		UsernameClaimed: "instagram",
	},
	"Lobsters": {
		ErrorType: "status_code",
		RegexCheck: "[A-Za-z0-9][A-Za-z0-9_-]{0,24}",
		URL: "https://lobste.rs/u/%s",
		URLMain: "https://lobste.rs/",
		UsernameClaimed: "jcs",
	},
	"forum_guns": {
		ErrorMsg: []string{
			"action=https://forum.guns.ru/forummisc/blog/search",
		},
		ErrorType: "message",
		URL: "https://forum.guns.ru/forummisc/blog/%s",
		URLMain: "https://forum.guns.ru/",
		UsernameClaimed: "red",
	},
	"irecommend": {
		ErrorType: "status_code",
		URL: "https://irecommend.ru/users/%s",
		URLMain: "https://irecommend.ru/",
		UsernameClaimed: "blue",
	},
	"mastodon.cloud": {
		ErrorType: "status_code",
		URL: "https://mastodon.cloud/@%s",
		URLMain: "https://mastodon.cloud/",
		UsernameClaimed: "TheAdmin",
	},
	"social.tchncs.de": {
		ErrorType: "status_code",
		URL: "https://social.tchncs.de/@%s",
		URLMain: "https://social.tchncs.de/",
		UsernameClaimed: "Milan",
	},
	"APClips": {
		ErrorMsg: []string{
			"Amateur Porn Content Creators",
		},
		ErrorType: "message",
		URL: "https://apclips.com/%s",
		URLMain: "https://apclips.com/",
		UsernameClaimed: "onlybbyraq",
		IsNSFW: true,
	},
	"Cults3D": {
		ErrorMsg: []string{
			"Oh dear, this page is not working!",
		},
		ErrorType: "message",
		URL: "https://cults3d.com/en/users/%s/creations",
		URLMain: "https://cults3d.com/en",
		UsernameClaimed: "brown",
	},
	"Imgur": {
		ErrorType: "status_code",
		URL: "https://imgur.com/user/%s",
		URLMain: "https://imgur.com/",
		URLProbe: "https://api.imgur.com/account/v1/accounts/%s?client_id=546c25a59c58ad7",
		UsernameClaimed: "blue",
	},
	"Rate Your Music": {
		ErrorType: "status_code",
		URL: "https://rateyourmusic.com/~%s",
		URLMain: "https://rateyourmusic.com/",
		UsernameClaimed: "blue",
	},
	"Redbubble": {
		ErrorType: "status_code",
		URL: "https://www.redbubble.com/people/%s",
		URLMain: "https://www.redbubble.com/",
		UsernameClaimed: "blue",
	},
	"WordPress": {
		ErrorType: "response_url",
		RegexCheck: "^[a-zA-Z][a-zA-Z0-9_-]*$",
		URL: "https://%s.wordpress.com/",
		URLMain: "https://wordpress.com",
		UsernameClaimed: "blue",
		ErrorURL: "wordpress.com/typo/?subdomain=",
	},
	"Xvideos": {
		ErrorType: "status_code",
		URL: "https://xvideos.com/profiles/%s",
		URLMain: "https://xvideos.com/",
		UsernameClaimed: "blue",
		IsNSFW: true,
	},
	"Bluesky": {
		ErrorType: "status_code",
		URL: "https://bsky.app/profile/%s.bsky.social",
		URLMain: "https://bsky.app/",
		URLProbe: "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor=%s.bsky.social",
		UsernameClaimed: "mcuban",
	},
	"CNET": {
		ErrorType: "status_code",
		RegexCheck: "^[a-z].*$",
		URL: "https://www.cnet.com/profiles/%s/",
		URLMain: "https://www.cnet.com/",
		UsernameClaimed: "melliott",
	},
	"Caddy Community": {
		ErrorType: "status_code",
		URL: "https://caddy.community/u/%s/summary",
		URLMain: "https://caddy.community/",
		UsernameClaimed: "taako_magnusen",
	},
	"Car Talk Community": {
		ErrorType: "status_code",
		URL: "https://community.cartalk.com/u/%s/summary",
		URLMain: "https://community.cartalk.com/",
		UsernameClaimed: "always_fixing",
	},
	"GoodReads": {
		ErrorType: "status_code",
		URL: "https://www.goodreads.com/%s",
		URLMain: "https://www.goodreads.com/",
		UsernameClaimed: "blue",
	},
	"Gutefrage": {
		ErrorType: "status_code",
		URL: "https://www.gutefrage.net/nutzer/%s",
		URLMain: "https://www.gutefrage.net/",
		UsernameClaimed: "gutefrage",
	},
	"Polymart": {
		ErrorType: "response_url",
		URL: "https://polymart.org/user/%s",
		URLMain: "https://polymart.org/",
		UsernameClaimed: "craciu25yt",
		ErrorURL: "https://polymart.org/user/-1",
	},
	"Roblox": {
		ErrorMsg: []string{
			"Page cannot be found or no longer exists",
		},
		ErrorType: "message",
		URL: "https://www.roblox.com/user.aspx?username=%s",
		URLMain: "https://www.roblox.com/",
		UsernameClaimed: "bluewolfekiller",
	},
	"Asciinema": {
		ErrorType: "status_code",
		URL: "https://asciinema.org/~%s",
		URLMain: "https://asciinema.org",
		UsernameClaimed: "red",
	},
	"Clubhouse": {
		ErrorType: "status_code",
		URL: "https://www.clubhouse.com/@%s",
		URLMain: "https://www.clubhouse.com",
		UsernameClaimed: "waniathar",
	},
	"Code Snippet Wiki": {
		ErrorMsg: []string{
			"This user has not filled out their profile page yet",
		},
		ErrorType: "message",
		URL: "https://codesnippets.fandom.com/wiki/User:%s",
		URLMain: "https://codesnippets.fandom.com",
		UsernameClaimed: "bob",
	},
	"Coderwall": {
		ErrorType: "status_code",
		URL: "https://coderwall.com/%s",
		URLMain: "https://coderwall.com",
		UsernameClaimed: "hacker",
	},
	"Holopin": {
		ErrorMsg: []string{
			"true",
		},
		ErrorType: "message",
		URL: "https://holopin.io/@%s",
		URLMain: "https://holopin.io",
		URLProbe: "https://www.holopin.io/api/auth/username",
		UsernameClaimed: "red",
		RequestMethod: "POST",
		RequestPayload: "{\"username\":\"%s\"}",
	},
	"Nextcloud Forum": {
		ErrorType: "status_code",
		RegexCheck: "^(?![.-])[a-zA-Z0-9_.-]{3,20}$",
		URL: "https://help.nextcloud.com/u/%s/summary",
		URLMain: "https://nextcloud.com/",
		UsernameClaimed: "blue",
	},
	"RuneScape": {
		ErrorMsg: []string{
			"{\"error\":\"NO_PROFILE\",\"loggedIn\":\"false\"}",
		},
		ErrorType: "message",
		RegexCheck: "^(?! )[\\w -]{1,12}(?<! )$",
		URL: "https://apps.runescape.com/runemetrics/app/overview/player/%s",
		URLMain: "https://www.runescape.com/",
		URLProbe: "https://apps.runescape.com/runemetrics/profile/profile?user=%s",
		UsernameClaimed: "L33",
	},
	"Trawelling": {
		ErrorType: "status_code",
		URL: "https://traewelling.de/@%s",
		URLMain: "https://traewelling.de/",
		UsernameClaimed: "lassestolley",
	},
	"Hackaday": {
		ErrorType: "status_code",
		URL: "https://hackaday.io/%s",
		URLMain: "https://hackaday.io/",
		UsernameClaimed: "adam",
	},
	"Jimdo": {
		ErrorType: "status_code",
		RegexCheck: "^[\\w@-]+?$",
		URL: "https://%s.jimdosite.com",
		URLMain: "https://jimdosite.com/",
		UsernameClaimed: "jenny",
	},
}
